-- R81 F2: index the anonymous `/invites/accept` lookup path.
--
-- The endpoint runs `WHERE email = ? AND acceptedAt IS NULL AND
-- revokedAt IS NULL AND expiresAt > now()` for every anonymous
-- POST. The composite UNIQUE (orgId, email) cannot serve
-- `email = ?` on its own (leftmost prefix is `orgId`), so
-- Postgres seq-scans the whole invites table per request. An
-- attacker who mass-invites the same email address (self-signup
-- is cheap) can bloat the table to millions of rows, then
-- hammer /invites/accept from any IP to force seq-scan-per-
-- request — I/O amplification sibling of the CPU DoS R80 F3
-- closed via `take: 5`. `take: 5` caps argon2 CPU; this index
-- caps the DB I/O.
--
-- Plain `CREATE INDEX` (not CONCURRENTLY): `prisma migrate
-- deploy` wraps each migration in a transaction, and
-- CONCURRENTLY cannot run inside a transaction — using it here
-- would break the deploy. This takes a SHARE lock on `invites`
-- for the duration of the build, blocking writes until it
-- completes. On an unbloated table the build is milliseconds;
-- if the DoS class this closes has already partially succeeded
-- before deploy, budget for INSERT/UPDATE stalls proportional
-- to table size (or split into two migrations with an explicit
-- transaction boundary and CONCURRENTLY on the second).
CREATE INDEX IF NOT EXISTS "invites_email_idx" ON "invites"("email");
