-- R81 F2: index the anonymous `/invites/accept` lookup path.
--
-- The endpoint runs `WHERE email = ? AND acceptedAt IS NULL AND
-- revokedAt IS NULL AND expiresAt > now()` for every anonymous
-- POST. The composite UNIQUE (orgId, email) cannot serve
-- `email = ?` on its own (leftmost prefix is `orgId`), so
-- Postgres seq-scans the whole invites table per request. An
-- attacker who mass-invites the same email address (self-signup
-- is cheap) can bloat the table to millions of rows, then
-- hammer /invites/accept from any IP to force seq-scan-per-
-- request — I/O amplification sibling of the CPU DoS R80 F3
-- closed via `take: 5`. `take: 5` caps argon2 CPU; this index
-- caps the DB I/O.
--
-- Plain `CREATE INDEX` (not CONCURRENTLY) is used because the
-- invites table is small at launch and the SHARE lock the build
-- takes is milliseconds. If the table grows large enough that
-- this becomes an operational concern, we can switch to
-- `CREATE INDEX CONCURRENTLY IF NOT EXISTS` in-place — Prisma
-- Migrate does NOT wrap `.sql` migration files in an implicit
-- transaction (upstream: prisma/prisma#6491), so CONCURRENTLY
-- runs cleanly under `prisma migrate deploy`. (The R82 revision
-- of this comment falsely claimed a transaction wrapper; the
-- migration deploys correctly either way, but the false premise
-- was misleading the next engineer's tool choice.)
CREATE INDEX IF NOT EXISTS "invites_email_idx" ON "invites"("email");
