//! `abctl init` / `abctl doctor` / `abctl health` — first-run setup and
//! environment diagnosis.
//!
//! `init` writes a provider-specific `agentbridge.toml` that the harness
//! picks up automatically (it is first in the config search path), then
//! prints copy-paste next steps. `doctor` re-resolves configuration the
//! exact same way the server does and checks every runtime prerequisite
//! without printing a single secret value. `health` probes a running
//! harness and is intended for container HEALTHCHECK directives.

use anyhow::{Context, Result};
use clap::ValueEnum;
use std::path::{Path, PathBuf};
use std::time::Duration;

/// Supported provider presets for `abctl init`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum Preset {
    /// OpenAI (api.openai.com).
    Openai,
    /// Azure OpenAI (custom deployment path + `api-key` header).
    Azure,
    /// Anthropic's OpenAI-compatible endpoint (api.anthropic.com).
    Anthropic,
    /// Google Gemini's OpenAI-compatible endpoint.
    Gemini,
    /// Groq (api.groq.com/openai).
    Groq,
    /// Mistral (api.mistral.ai).
    Mistral,
    /// OpenRouter (openrouter.ai/api).
    Openrouter,
    /// Together AI (api.together.xyz).
    Together,
    /// DeepSeek (api.deepseek.com).
    Deepseek,
    /// xAI Grok (api.x.ai).
    Xai,
    /// Local Ollama (127.0.0.1:11434, no key).
    Ollama,
    /// Local LM Studio (127.0.0.1:1234, no key).
    Lmstudio,
    /// Local vLLM OpenAI server (127.0.0.1:8000, no key).
    Vllm,
    /// Local llama.cpp server (127.0.0.1:8080, no key).
    Llamacpp,
    /// LiteLLM gateway (127.0.0.1:4000).
    Litellm,
    /// Custom endpoint: supply --upstream-url yourself.
    Custom,
}

struct PresetSpec {
    upstream_url: &'static str,
    chat_path: Option<&'static str>,
    key_env: Option<&'static str>,
    auth_header: Option<&'static str>,
    /// `Some("")` means "raw key, no scheme prefix".
    auth_scheme: Option<&'static str>,
    notes: &'static [&'static str],
}

fn spec(preset: Preset) -> PresetSpec {
    let plain = |url, env| PresetSpec {
        upstream_url: url,
        chat_path: None,
        key_env: env,
        auth_header: None,
        auth_scheme: None,
        notes: &[],
    };
    match preset {
        Preset::Openai => plain("https://api.openai.com", Some("OPENAI_API_KEY")),
        Preset::Azure => PresetSpec {
            upstream_url: "https://YOUR-RESOURCE.openai.azure.com",
            chat_path: Some("/openai/deployments/YOUR-DEPLOYMENT/chat/completions?api-version=2024-10-21"),
            key_env: Some("AZURE_OPENAI_API_KEY"),
            auth_header: Some("api-key"),
            auth_scheme: Some(""),
            notes: &[
                "Replace YOUR-RESOURCE with your Azure OpenAI resource name.",
                "Replace YOUR-DEPLOYMENT with your model deployment name.",
            ],
        },
        Preset::Anthropic => plain("https://api.anthropic.com", Some("ANTHROPIC_API_KEY")),
        Preset::Gemini => PresetSpec {
            upstream_url: "https://generativelanguage.googleapis.com/v1beta/openai",
            chat_path: Some("/chat/completions"),
            key_env: Some("GEMINI_API_KEY"),
            auth_header: None,
            auth_scheme: None,
            notes: &[],
        },
        Preset::Groq => plain("https://api.groq.com/openai", Some("GROQ_API_KEY")),
        Preset::Mistral => plain("https://api.mistral.ai", Some("MISTRAL_API_KEY")),
        Preset::Openrouter => plain("https://openrouter.ai/api", Some("OPENROUTER_API_KEY")),
        Preset::Together => plain("https://api.together.xyz", Some("TOGETHER_API_KEY")),
        Preset::Deepseek => plain("https://api.deepseek.com", Some("DEEPSEEK_API_KEY")),
        Preset::Xai => plain("https://api.x.ai", Some("XAI_API_KEY")),
        Preset::Ollama => plain("http://127.0.0.1:11434", None),
        Preset::Lmstudio => plain("http://127.0.0.1:1234", None),
        Preset::Vllm => plain("http://127.0.0.1:8000", None),
        Preset::Llamacpp => plain("http://127.0.0.1:8080", None),
        Preset::Litellm => plain("http://127.0.0.1:4000", Some("LITELLM_MASTER_KEY")),
        Preset::Custom => PresetSpec {
            upstream_url: "",
            chat_path: None,
            key_env: None,
            auth_header: None,
            auth_scheme: None,
            notes: &["Pass --key-env NAME if the endpoint needs an API key."],
        },
    }
}

/// Render the annotated TOML for a preset.
fn render_config(preset: Preset, upstream_url: &str, key_env: Option<&str>) -> String {
    let spec = spec(preset);
    let mut out = String::new();
    out.push_str("# AgentBridge harness configuration (generated by `abctl init`).\n");
    out.push_str("# Every omitted field keeps a safe default; see config/harness.example.toml\n");
    out.push_str("# in the AgentBridge repository for the full annotated reference.\n\n");
    out.push_str("config_version = 1\n\n");
    out.push_str("# Address the proxy listens on. Use \"0.0.0.0:8484\" inside containers.\n");
    out.push_str("listen = \"127.0.0.1:8484\"\n\n");
    out.push_str("# OpenAI-compatible provider base URL.\n");
    out.push_str(&format!("upstream_url = \"{upstream_url}\"\n"));
    if let Some(path) = spec.chat_path {
        out.push_str("# Provider-specific chat completions path.\n");
        out.push_str(&format!("upstream_chat_path = \"{path}\"\n"));
    }
    if let Some(env) = key_env {
        out.push_str("\n# API key is read from this environment variable at startup.\n");
        out.push_str("# (Alternative: upstream_api_key_file = \"/path/to/key\" with mode 0600.)\n");
        out.push_str(&format!("upstream_api_key_env = \"{env}\"\n"));
    } else {
        out.push_str("\n# No API key needed for this endpoint. To add one later:\n");
        out.push_str("#   upstream_api_key_env = \"PROVIDER_API_KEY\"\n");
    }
    if let Some(header) = spec.auth_header {
        out.push_str(&format!("upstream_auth_header = \"{header}\"\n"));
    }
    if let Some(scheme) = spec.auth_scheme {
        out.push_str("# Empty scheme sends the key raw (no \"Bearer \" prefix).\n");
        out.push_str(&format!("upstream_auth_scheme = \"{scheme}\"\n"));
    }
    out.push_str("\n# Signed receipts, OCSF events, and ATIF trajectories are written here.\n");
    out.push_str("atif_spool_dir = \"data/spool\"\n");
    out.push_str("bridge_data_dir = \"data/bridge\"\n");
    out
}

/// `abctl init` — write a provider-specific config and print next steps.
pub fn init(
    preset: Preset,
    output: &Path,
    force: bool,
    upstream_url: Option<&str>,
    key_env: Option<&str>,
) -> Result<()> {
    let spec_defaults = spec(preset);
    let upstream_url = match (upstream_url, spec_defaults.upstream_url) {
        (Some(url), _) => url.to_owned(),
        (None, "") => anyhow::bail!("--preset custom requires --upstream-url"),
        (None, default) => default.to_owned(),
    };
    // The values are interpolated into TOML below: reject anything that
    // could escape the string literal (quote, backslash, control bytes)
    // instead of silently writing a config that means something else.
    if !upstream_url.starts_with("http://") && !upstream_url.starts_with("https://") {
        anyhow::bail!("--upstream-url must start with http:// or https://");
    }
    if upstream_url
        .chars()
        .any(|c| c == '"' || c == '\\' || c.is_control() || c == ' ')
    {
        anyhow::bail!("--upstream-url contains characters not allowed in a URL");
    }
    let key_env = key_env
        .map(str::to_owned)
        .or_else(|| spec_defaults.key_env.map(str::to_owned));
    if let Some(env) = &key_env {
        let valid = !env.is_empty()
            && !env.starts_with(|c: char| c.is_ascii_digit())
            && env.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
        if !valid {
            anyhow::bail!("--key-env must be a valid environment variable name, got {env:?}");
        }
    }
    let rendered = render_config(preset, &upstream_url, key_env.as_deref());
    // Refuse to write anything the harness itself would reject.
    ab_harness::HarnessConfig::from_toml(&rendered)
        .map_err(|error| anyhow::anyhow!("generated config failed validation (bug): {error}"))?;
    if output.exists() && !force {
        anyhow::bail!("{} already exists; pass --force to overwrite", output.display());
    }
    if let Some(parent) = output.parent().filter(|p| !p.as_os_str().is_empty()) {
        std::fs::create_dir_all(parent).with_context(|| format!("create directory {}", parent.display()))?;
    }
    std::fs::write(output, &rendered).with_context(|| format!("write {}", output.display()))?;
    println!("wrote {}", output.display());
    for note in spec_defaults.notes {
        println!("note: {note}");
    }
    println!();
    println!("Next steps:");
    let mut step = 1;
    if let Some(env) = &key_env {
        println!("  {step}. export {env}=<your api key>");
        step += 1;
    }
    if preset == Preset::Azure {
        println!(
            "  {step}. edit {} and fill in your resource + deployment",
            output.display()
        );
        step += 1;
    }
    println!("  {step}. agent-bridge        # starts on 127.0.0.1:8484");
    step += 1;
    println!("  {step}. point your OpenAI-compatible client at http://127.0.0.1:8484/v1");
    println!();
    println!("Check the environment any time with: abctl doctor");
    Ok(())
}

/// One diagnostic line: pass/warn/fail plus a short explanation.
enum Check {
    Pass(String),
    Warn(String),
    Fail(String),
}

fn report(checks: &[Check]) -> (usize, usize) {
    let mut warnings = 0;
    let mut failures = 0;
    for check in checks {
        match check {
            Check::Pass(message) => println!("  ok    {message}"),
            Check::Warn(message) => {
                warnings += 1;
                println!("  warn  {message}");
            }
            Check::Fail(message) => {
                failures += 1;
                println!("  FAIL  {message}");
            }
        }
    }
    (warnings, failures)
}

/// `abctl doctor` — resolve config exactly like the server and verify every
/// runtime prerequisite. Never prints secret values, only source names.
pub async fn doctor(offline: bool) -> Result<()> {
    let mut checks = Vec::new();

    // 1. Config resolution (same search order as the server).
    let resolved = ab_harness::config::load_config();
    let config = match resolved {
        Ok((config, source)) => {
            checks.push(Check::Pass(format!("config: {source}")));
            Some(config)
        }
        Err(error) => {
            checks.push(Check::Fail(format!("config: {error}")));
            None
        }
    };

    if let Some(config) = &config {
        // 2. Common URL footgun: base URL already contains the chat path
        // prefix (e.g. ".../v1" + "/v1/chat/completions").
        if let Some(segment) = config.duplicated_chat_path_segment() {
            checks.push(Check::Warn(format!(
                "upstream_url ends with \"/{segment}\" and upstream_chat_path repeats it; \
                 the joined URL will contain \"/{segment}/{segment}/\" — drop the suffix from upstream_url"
            )));
        }

        // 3. Upstream auth source (names only, never values).
        let auth = ab_harness::pipeline::describe_upstream_auth(config);
        if let Some(env) = &config.upstream_api_key_env {
            match std::env::var(env) {
                Ok(value) if !value.trim().is_empty() => {
                    checks.push(Check::Pass(format!("upstream auth: {auth} (set)")));
                }
                _ => checks.push(Check::Fail(format!(
                    "upstream auth: {auth} — environment variable {env} is unset or empty"
                ))),
            }
        } else if let Some(file) = &config.upstream_api_key_file {
            match std::fs::metadata(file) {
                Ok(_) => checks.push(Check::Pass(format!("upstream auth: {auth}"))),
                Err(error) => {
                    checks.push(Check::Fail(format!("upstream auth: {auth} — {error}")));
                }
            }
        } else {
            checks.push(Check::Pass(format!("upstream auth: {auth}")));
        }

        // 4. Upstream reachability (TCP + HTTP; any HTTP status counts).
        if offline {
            checks.push(Check::Warn("upstream: skipped (--offline)".to_owned()));
        } else {
            let url = config.upstream_url.trim_end_matches('/').to_owned();
            let client = reqwest::Client::builder()
                .redirect(reqwest::redirect::Policy::none())
                .timeout(Duration::from_secs(3))
                .build()
                .context("build probe client")?;
            match client.get(&url).send().await {
                Ok(response) => checks.push(Check::Pass(format!(
                    "upstream: {url} reachable (HTTP {})",
                    response.status().as_u16()
                ))),
                Err(error) => {
                    // Sanitize: reqwest Display includes the URL, never a key.
                    checks.push(Check::Fail(format!("upstream: {url} unreachable ({error})")));
                }
            }
        }

        // 5. Bridge manifest.
        match std::fs::read_to_string(&config.bridge_manifest_path) {
            Ok(text) => match ab_bridge::BridgeManifest::from_yaml(&text) {
                Ok(manifest) => checks.push(Check::Pass(format!(
                    "manifest: {} ({} topics)",
                    config.bridge_manifest_path,
                    manifest.topics.len()
                ))),
                Err(error) => checks.push(Check::Fail(format!(
                    "manifest: {} invalid: {error}",
                    config.bridge_manifest_path
                ))),
            },
            Err(_) if config.uses_default_manifest_path() => checks.push(Check::Pass(
                "manifest: using embedded built-in (no file on disk)".to_owned(),
            )),
            Err(error) => checks.push(Check::Fail(format!(
                "manifest: {}: {error}",
                config.bridge_manifest_path
            ))),
        }

        // 6. WASM policies.
        for path in &config.wasm_policy_paths {
            if Path::new(path).is_file() {
                checks.push(Check::Pass(format!("policy: {path}")));
            } else if ab_harness::HarnessConfig::is_default_policy_path(path) {
                checks.push(Check::Pass(format!("policy: {path} (embedded built-in)")));
            } else {
                checks.push(Check::Fail(format!("policy: {path} not found")));
            }
        }

        // 7. Tool schemas.
        match config.tool_schema_dir.as_deref() {
            Some(dir) => match std::fs::read_dir(dir) {
                Ok(entries) => {
                    let count = entries
                        .filter_map(Result::ok)
                        .filter(|e| e.path().extension().is_some_and(|x| x == "json"))
                        .count();
                    if count > 0 {
                        checks.push(Check::Pass(format!("tool schemas: {count} in {dir}")));
                    } else if config.tool_upstream_url.is_some() {
                        checks.push(Check::Fail(format!(
                            "tool schemas: none in {dir} but tool_upstream_url is set"
                        )));
                    } else {
                        checks.push(Check::Warn(format!(
                            "tool schemas: none in {dir}; tool calls will be rejected"
                        )));
                    }
                }
                Err(_) if config.uses_default_tool_schema_dir() => checks.push(Check::Warn(
                    "tool schemas: default directory missing; tool calls will be rejected".to_owned(),
                )),
                Err(error) => checks.push(Check::Fail(format!("tool schemas: {dir}: {error}"))),
            },
            None => checks.push(Check::Warn(
                "tool schemas: no directory configured; tool calls will be rejected".to_owned(),
            )),
        }

        // 8. Signing seed (created on first run if absent).
        let seed_path = std::env::var_os("AB_SIGNING_SEED_FILE")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("config/signing.seed"));
        if seed_path.is_file() {
            #[cfg(unix)]
            {
                use std::os::unix::fs::MetadataExt as _;
                match std::fs::symlink_metadata(&seed_path) {
                    Ok(meta) if meta.file_type().is_symlink() => checks.push(Check::Fail(format!(
                        "signing seed: {} is a symbolic link",
                        seed_path.display()
                    ))),
                    Ok(meta) if meta.mode() & 0o077 != 0 => checks.push(Check::Fail(format!(
                        "signing seed: {} is group/world accessible (chmod 600 it)",
                        seed_path.display()
                    ))),
                    Ok(_) => checks.push(Check::Pass(format!("signing seed: {}", seed_path.display()))),
                    Err(error) => {
                        checks.push(Check::Fail(format!(
                            "signing seed: {}: {error}",
                            seed_path.display()
                        )));
                    }
                }
            }
            #[cfg(not(unix))]
            checks.push(Check::Pass(format!("signing seed: {}", seed_path.display())));
        } else {
            checks.push(Check::Pass(format!(
                "signing seed: {} will be generated on first run",
                seed_path.display()
            )));
        }

        // 9. Data directories writable (created on demand by the server).
        for (label, dir) in [
            ("spool dir", config.atif_spool_dir.as_str()),
            ("bridge dir", config.bridge_data_dir.as_str()),
        ] {
            let path = Path::new(dir);
            let probe_parent = if path.exists() {
                path.to_path_buf()
            } else {
                // Find the nearest existing ancestor to test writability.
                let mut ancestor = path.to_path_buf();
                while !ancestor.exists() {
                    match ancestor.parent() {
                        Some(parent) if !parent.as_os_str().is_empty() => {
                            ancestor = parent.to_path_buf();
                        }
                        _ => {
                            ancestor = PathBuf::from(".");
                            break;
                        }
                    }
                }
                ancestor
            };
            // A real create+delete probe: permission bits alone lie about
            // ownership, ACLs, and read-only mounts.
            let probe = probe_parent.join(format!(".abctl-doctor-{}", std::process::id()));
            match std::fs::OpenOptions::new()
                .write(true)
                .create_new(true)
                .open(&probe)
            {
                Ok(_) => {
                    let _ = std::fs::remove_file(&probe);
                    checks.push(Check::Pass(format!("{label}: {dir}")));
                }
                Err(error) => checks.push(Check::Fail(format!(
                    "{label}: cannot write in {} ({error})",
                    probe_parent.display()
                ))),
            }
        }

        // 10. Backend endpoints (TCP probe only; skipped offline).
        if !offline {
            for (label, endpoint) in [
                ("state (redis)", config.state_endpoint.as_deref()),
                ("bridge endpoint", config.bridge_endpoint.as_deref()),
                ("qdrant", config.qdrant_url.as_deref()),
            ] {
                let Some(endpoint) = endpoint.filter(|e| !e.is_empty()) else {
                    continue;
                };
                match probe_endpoint(endpoint).await {
                    Ok(()) => checks.push(Check::Pass(format!("{label}: {endpoint} reachable"))),
                    Err(error) => {
                        checks.push(Check::Fail(format!("{label}: {endpoint} unreachable ({error})")));
                    }
                }
            }
        }

        // 11. Identity posture.
        if config.require_identity {
            checks.push(Check::Pass("identity: required (production posture)".to_owned()));
        } else {
            checks.push(Check::Warn(
                "identity: optional (dev mode; set require_identity=true in production)".to_owned(),
            ));
        }
    }

    println!("abctl doctor");
    let (warnings, failures) = report(&checks);
    println!();
    if failures > 0 {
        anyhow::bail!("{failures} check(s) failed, {warnings} warning(s)");
    }
    println!("all checks passed ({warnings} warning(s))");
    Ok(())
}

/// TCP-connect to `host:port` extracted from a URL or bare `host:port`.
async fn probe_endpoint(endpoint: &str) -> Result<()> {
    let target = match endpoint.split_once("://") {
        Some((_, rest)) => rest.split(['/', '?']).next().unwrap_or(rest),
        None => endpoint,
    };
    let target = if target.contains(':') {
        target.to_owned()
    } else {
        // Scheme-driven default port for schemeless probing.
        format!("{target}:80")
    };
    tokio::time::timeout(Duration::from_secs(3), tokio::net::TcpStream::connect(&target))
        .await
        .map_err(|_| anyhow::anyhow!("timeout"))?
        .map(|_| ())
        .map_err(anyhow::Error::from)
}

/// `abctl health` — probe a running harness; exit 0 only on HTTP 200.
pub async fn health(base_url: &str) -> Result<()> {
    let url = format!("{}/health", base_url.trim_end_matches('/'));
    let client = reqwest::Client::builder()
        .redirect(reqwest::redirect::Policy::none())
        .timeout(Duration::from_secs(3))
        .build()
        .context("build health client")?;
    let response = client
        .get(&url)
        .send()
        .await
        .with_context(|| format!("GET {url}"))?;
    if !response.status().is_success() {
        anyhow::bail!("harness unhealthy: HTTP {}", response.status().as_u16());
    }
    println!("healthy {url}");
    Ok(())
}

#[cfg(test)]
mod tests {
    #![allow(clippy::panic, clippy::unwrap_used)]

    use super::*;

    #[test]
    fn every_preset_generates_a_valid_config() {
        for preset in [
            Preset::Openai,
            Preset::Azure,
            Preset::Anthropic,
            Preset::Gemini,
            Preset::Groq,
            Preset::Mistral,
            Preset::Openrouter,
            Preset::Together,
            Preset::Deepseek,
            Preset::Xai,
            Preset::Ollama,
            Preset::Lmstudio,
            Preset::Vllm,
            Preset::Llamacpp,
            Preset::Litellm,
        ] {
            let s = spec(preset);
            let rendered = render_config(preset, s.upstream_url, s.key_env);
            let config = ab_harness::HarnessConfig::from_toml(&rendered)
                .unwrap_or_else(|error| panic!("{preset:?}: {error}"));
            assert!(!config.upstream_url.is_empty(), "{preset:?} upstream_url");
        }
        // Custom with an explicit URL also validates.
        let rendered = render_config(Preset::Custom, "http://10.0.0.5:9000", Some("MY_KEY"));
        ab_harness::HarnessConfig::from_toml(&rendered).unwrap();
    }

    #[test]
    fn azure_preset_uses_raw_key_header() {
        let s = spec(Preset::Azure);
        let rendered = render_config(Preset::Azure, s.upstream_url, s.key_env);
        let config = ab_harness::HarnessConfig::from_toml(&rendered).unwrap();
        assert_eq!(config.upstream_auth_header, "api-key");
        assert_eq!(config.upstream_auth_scheme, "");
        assert!(config.upstream_chat_path.starts_with("/openai/deployments/"));
        assert_eq!(
            config.upstream_api_key_env.as_deref(),
            Some("AZURE_OPENAI_API_KEY")
        );
    }

    #[test]
    fn local_presets_need_no_key() {
        for preset in [Preset::Ollama, Preset::Lmstudio, Preset::Vllm, Preset::Llamacpp] {
            let s = spec(preset);
            assert!(s.key_env.is_none(), "{preset:?} must not demand a key");
            let rendered = render_config(preset, s.upstream_url, s.key_env);
            let config = ab_harness::HarnessConfig::from_toml(&rendered).unwrap();
            assert!(config.upstream_api_key_env.is_none());
            assert!(config.upstream_api_key_file.is_none());
        }
    }

    #[test]
    fn init_writes_and_refuses_overwrite() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("agentbridge.toml");
        init(Preset::Ollama, &path, false, None, None).unwrap();
        assert!(path.is_file());
        let error = init(Preset::Ollama, &path, false, None, None).unwrap_err();
        assert!(error.to_string().contains("--force"), "{error}");
        init(Preset::Openai, &path, true, None, None).unwrap();
        let text = std::fs::read_to_string(&path).unwrap();
        assert!(text.contains("api.openai.com"));
    }

    #[test]
    fn custom_preset_requires_url() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("agentbridge.toml");
        let error = init(Preset::Custom, &path, false, None, None).unwrap_err();
        assert!(error.to_string().contains("--upstream-url"), "{error}");
    }

    /// User-supplied values are interpolated into TOML: anything that could
    /// escape the string literal must be rejected, not written.
    #[test]
    fn init_rejects_toml_injection_attempts() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("agentbridge.toml");
        for url in [
            "http://x\"\nrequire_identity = false #", // quote escape
            "http://x\\y",                            // backslash escape
            "ftp://host",                             // wrong scheme
            "api.openai.com",                         // missing scheme
            "http://x y",                             // embedded space
        ] {
            let error = init(Preset::Custom, &path, true, Some(url), None).unwrap_err();
            assert!(!path.exists(), "{url:?} must not produce a file: {error}");
        }
        for env in ["MY KEY", "1KEY", "KEY\"X", "", "KEY-NAME"] {
            let error = init(
                Preset::Custom,
                &path,
                true,
                Some("http://127.0.0.1:9000"),
                Some(env),
            )
            .unwrap_err();
            assert!(error.to_string().contains("--key-env"), "{env:?}: {error}");
            assert!(!path.exists(), "{env:?} must not produce a file");
        }
        // Sane values still pass.
        init(
            Preset::Custom,
            &path,
            true,
            Some("http://127.0.0.1:9000"),
            Some("MY_KEY_9"),
        )
        .unwrap();
        assert!(path.exists());
    }
}
